### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by stef204** [c4ffein/OOS-firmware-updater#3]
~~I cannot understand the instructions in the README file, the various steps to take are not clear.~~
N/A -- please delete.

**Comment by c4ffein** [comment]
@stef204 Just in case, I still saw your issue in my mails and updated the README. You may be concerned by what is in the Contributing section.

**Comment by stef204** [comment]
Yes, I saw the changes you made and they help. I posted the issue **prior** to installing the app and it got me confused as to the steps.  Once I installed the app, I could understand what the various steps meant.  That's why I "deleted" the issue.  The details you added do help though.

PS  Feel free to delete this issue.  Thanks.
